# Generated by Django 5.1.15 on 2026-04-11 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última modificación del registro.')),
                ('target_url', models.URLField(help_text='URL original enviada por el usuario.', max_length=2048, verbose_name='target URL')),
                ('normalized_host', models.CharField(blank=True, help_text='Hostname extraído tras validar la URL.', max_length=253, verbose_name='hostname')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Puntuación 0-100 calculada al finalizar.', null=True, verbose_name='score')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Outputs crudos de cada scanner para debug y re-scoring.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit',
                'verbose_name_plural': 'audits',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última modificación del registro.')),
                ('category', models.CharField(choices=[('dns', 'DNS'), ('transport', 'Transport / TLS'), ('headers', 'HTTP Headers'), ('cookies', 'Cookies'), ('ports', 'Open Ports'), ('vulns', 'Vulnerabilities')], db_index=True, max_length=16, verbose_name='category')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=16, verbose_name='severity')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Datos concretos que soportan el hallazgo.', verbose_name='evidence')),
                ('recommendation', models.TextField(blank=True, default='', verbose_name='recommendation')),
                ('reference_url', models.URLField(blank=True, default='', verbose_name='reference URL')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.audit')),
            ],
            options={
                'verbose_name': 'finding',
                'verbose_name_plural': 'findings',
                'ordering': ('severity',),
            },
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['user', '-created_at'], name='audits_audi_user_id_261459_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['audit', 'severity'], name='audits_find_audit_i_721a85_idx'),
        ),
    ]
