# Generated by Django 5.1.15 on 2026-04-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='scan_mode',
            field=models.CharField(choices=[('passive', 'Passive'), ('active', 'Active')], default='passive', help_text='Pasivo = solo observa. Activo = envía payloads de prueba.', max_length=16, verbose_name='scan mode'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='category',
            field=models.CharField(choices=[('dns', 'DNS'), ('transport', 'Transport / TLS'), ('headers', 'HTTP Headers'), ('cookies', 'Cookies'), ('ports', 'Open Ports'), ('vulns', 'Vulnerabilities'), ('recon', 'Reconnaissance'), ('misconfig', 'Misconfigurations')], db_index=True, max_length=16, verbose_name='category'),
        ),
    ]
