# Generated by Django 5.1.15 on 2026-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_add_scan_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='selected_scanners',
            field=models.JSONField(blank=True, default=list, help_text='Lista de scanner keys seleccionados por el usuario. Vacío = ejecutar todos los disponibles según plan y modo.', verbose_name='selected scanners'),
        ),
    ]
