# Generated by Django 5.1.15 on 2026-04-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_alter_finding_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='category',
            field=models.CharField(choices=[('dns', 'DNS'), ('transport', 'Transport / TLS'), ('headers', 'HTTP Headers'), ('cookies', 'Cookies'), ('ports', 'Open Ports'), ('vulns', 'Vulnerabilities'), ('recon', 'Reconnaissance'), ('misconfig', 'Misconfigurations'), ('access', 'Broken Access Control'), ('crypto', 'Cryptographic Failures'), ('design', 'Insecure Design'), ('components', 'Vulnerable Components'), ('auth', 'Authentication Failures'), ('integrity', 'Software Integrity'), ('logging', 'Logging & Monitoring'), ('ssrf', 'SSRF'), ('js', 'JavaScript Analysis')], db_index=True, max_length=16, verbose_name='category'),
        ),
    ]
