# Generated by Django 5.1.15 on 2026-04-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_alter_finding_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='selected_scanners',
            field=models.JSONField(blank=True, default=list, help_text='Lista de scanner keys seleccionados por el usuario. Vacío = ejecutar todos los disponibles según modo.', verbose_name='selected scanners'),
        ),
    ]
