# Generated by Django 5.1.15 on 2026-04-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorchange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.'),
        ),
        migrations.AlterField(
            model_name='monitorchange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última modificación del registro.'),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.'),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última modificación del registro.'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última modificación del registro.'),
        ),
    ]
