# Generated by Django 5.1.15 on 2026-04-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_extended_security_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorchange',
            name='change_type',
            field=models.CharField(choices=[('status_down', 'Target went OFFLINE'), ('status_up', 'Target came back ONLINE'), ('http_status', 'HTTP status code changed'), ('response_slow', 'Response time degraded'), ('redirect_change', 'Redirect chain changed'), ('header_added', 'Security header added'), ('header_removed', 'Security header removed'), ('header_changed', 'Security header value changed'), ('ssl_expiry_warn', 'SSL certificate expiring soon'), ('ssl_expiry_chg', 'SSL certificate renewed/changed'), ('content_changed', 'Page content changed'), ('tech_added', 'Technology detected'), ('tech_removed', 'Technology removed'), ('waf_appeared', 'WAF/CDN appeared'), ('waf_gone', 'WAF/CDN disappeared'), ('sensitive_path', 'Sensitive path exposed'), ('score_drop', 'Security score dropped')], max_length=24),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='headers_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Security headers capturados en este check.'),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='security_score',
            field=models.IntegerField(blank=True, help_text='Puntuación 0-100 de la postura de seguridad.', null=True, verbose_name='security score'),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='waf_detected',
            field=models.CharField(blank=True, default='', help_text='WAF o CDN detectado en los response headers.', max_length=64, verbose_name='WAF/CDN'),
        ),
    ]
